interface CldrCode {
  cldrCode: string;
  label: string;
  ucumCode: string | null;
}

export const cldrCodes: CldrCode[] = [
  {
    cldrCode: "acceleration-g-force",
    label: "acceleration due to gravity",
    ucumCode: "[g]",
  },
  {
    cldrCode: "acceleration-meter-per-square-second",
    label: "meter per square second",
    ucumCode: "m/s2",
  },
  { cldrCode: "angle-arc-minute", label: "minute (angle)", ucumCode: "'" },
  { cldrCode: "angle-arc-second", label: "second (angle)", ucumCode: "''" },
  { cldrCode: "angle-degree", label: "degree (angle)", ucumCode: "deg" },
  { cldrCode: "angle-radian", label: "radian", ucumCode: "rad" },
  { cldrCode: "angle-revolution", label: "circle", ucumCode: "circ" },
  { cldrCode: "area-acre", label: "acre", ucumCode: "[acr_us]" },
  { cldrCode: "area-hectare", label: "hectare", ucumCode: "har" },
  {
    cldrCode: "area-square-centimeter",
    label: "square centimeter",
    ucumCode: "cm2",
  },
  { cldrCode: "area-square-foot", label: "square foot", ucumCode: "[sft_i]" },
  { cldrCode: "area-square-inch", label: "square inch", ucumCode: "[sin_i]" },
  {
    cldrCode: "area-square-kilometer",
    label: "square kilometer",
    ucumCode: "km2",
  },
  { cldrCode: "area-square-meter", label: "square meter", ucumCode: "m2" },
  { cldrCode: "area-square-mile", label: "square mile", ucumCode: "[smi_us]" },
  { cldrCode: "area-square-yard", label: "square yard", ucumCode: "[syd_i]" },
  { cldrCode: "area-dunam", label: "dunam", ucumCode: null },
  { cldrCode: "concentr-karat", label: "karat", ucumCode: "[car_Au]" },
  {
    cldrCode: "concentr-milligram-ofglucose-per-deciliter",
    label: "milligram glucose per deciliter",
    ucumCode: "mg{Glucose}/dL",
  },
  {
    cldrCode: "concentr-millimole-per-liter",
    label: "millimole per liter",
    ucumCode: "mmol/L",
  },
  { cldrCode: "concentr-percent", label: "percent", ucumCode: "%" },
  { cldrCode: "concentr-permille", label: "per mille", ucumCode: "/10*3" },
  { cldrCode: "concentr-permyriad", label: "permyriad", ucumCode: "/10*5" },
  {
    cldrCode: "concentr-permillion",
    label: "per million",
    ucumCode: "/10*6",
  },
  { cldrCode: "concentr-mole", label: "mole", ucumCode: "mol" },
  { cldrCode: "concentr-item", label: "item", ucumCode: null },
  { cldrCode: "concentr-portion", label: "portion", ucumCode: null },
  { cldrCode: "concentr-ofglucose", label: "unit of glucose", ucumCode: null },
  {
    cldrCode: "consumption-liter-per-100-kilometer",
    label: "liter per 100 kilometer",
    ucumCode: "L/(100.km)",
  },
  {
    cldrCode: "consumption-liter-per-kilometer",
    label: "liter per kilometer",
    ucumCode: "L/km",
  },
  {
    cldrCode: "consumption-mile-per-gallon",
    label: "mile per gallon",
    ucumCode: "[mi_i]/[gal_us]",
  },
  {
    cldrCode: "consumption-mile-per-gallon-imperial",
    label: "mile per imperial gallon",
    ucumCode: "[mi_i]/[gal_br]",
  },
  { cldrCode: "digital-bit", label: "bit", ucumCode: "bit" },
  { cldrCode: "digital-byte", label: "byte", ucumCode: "By" },
  { cldrCode: "digital-gigabit", label: "gigabit", ucumCode: "Gbit" },
  { cldrCode: "digital-gigabyte", label: "gigabyte", ucumCode: "GBy" },
  { cldrCode: "digital-kilobit", label: "kilobit", ucumCode: "kbit" },
  { cldrCode: "digital-kilobyte", label: "kilobyte", ucumCode: "kBy" },
  { cldrCode: "digital-megabit", label: "megabit", ucumCode: "Mbit" },
  { cldrCode: "digital-megabyte", label: "megabyte", ucumCode: "MBy" },
  { cldrCode: "digital-petabyte", label: "petabyte", ucumCode: "PBy" },
  { cldrCode: "digital-terabit", label: "terabit", ucumCode: "Tbit" },
  { cldrCode: "digital-terabyte", label: "terabyte", ucumCode: "TBy" },
  { cldrCode: "duration-century", label: "century", ucumCode: null },
  { cldrCode: "duration-decade", label: "decade", ucumCode: null },
  { cldrCode: "duration-day", label: "day", ucumCode: "d" },
  { cldrCode: "duration-day-person", label: "person-day", ucumCode: null },
  { cldrCode: "duration-hour", label: "hour", ucumCode: "h" },
  { cldrCode: "duration-microsecond", label: "microsecond", ucumCode: "us" },
  { cldrCode: "duration-millisecond", label: "millisecond", ucumCode: "ms" },
  { cldrCode: "duration-minute", label: "minute", ucumCode: "min" },
  { cldrCode: "duration-month", label: "month", ucumCode: "mo" },
  { cldrCode: "duration-month-person", label: "person-month", ucumCode: null },
  { cldrCode: "duration-nanosecond", label: "nanosecond", ucumCode: "ns" },
  { cldrCode: "duration-quarter", label: "quarter", ucumCode: null },
  { cldrCode: "duration-second", label: "second", ucumCode: "s" },
  { cldrCode: "duration-week", label: "week", ucumCode: "wk" },
  { cldrCode: "duration-week-person", label: "person-week", ucumCode: null },
  { cldrCode: "duration-year", label: "year", ucumCode: "a" },
  { cldrCode: "duration-year-person", label: "person-year", ucumCode: null },
  { cldrCode: "electric-ampere", label: "ampere", ucumCode: "A" },
  { cldrCode: "electric-milliampere", label: "milliampere", ucumCode: "mA" },
  { cldrCode: "electric-ohm", label: "ohm", ucumCode: "Ohm" },
  { cldrCode: "electric-volt", label: "volt", ucumCode: "V" },
  { cldrCode: "energy-calorie", label: "calorie", ucumCode: "cal" },
  {
    cldrCode: "energy-foodcalorie",
    label: "nutrition label calorie",
    ucumCode: "[Cal]",
  },
  { cldrCode: "energy-joule", label: "joule", ucumCode: "J" },
  { cldrCode: "energy-kilocalorie", label: "kilocalorie", ucumCode: "kcal" },
  { cldrCode: "energy-kilojoule", label: "kilojoule", ucumCode: "kJ" },
  {
    cldrCode: "energy-kilowatt-hour",
    label: "kilowatt hour",
    ucumCode: "kW.h",
  },
  { cldrCode: "energy-electronvolt", label: "electronvolt", ucumCode: "eV" },
  { cldrCode: "energy-therm-us", label: "therm", ucumCode: null },
  {
    cldrCode: "energy-british-thermal-unit",
    label: "british thermal unit",
    ucumCode: "[Btu]",
  },
  { cldrCode: "force-pound-force", label: "pound force", ucumCode: "[lbf_av]" },
  { cldrCode: "force-newton", label: "newton", ucumCode: "N" },
  {
    cldrCode: "force-kilowatt-hour-per-100-kilometer",
    label: "kilowatt-hour per 100 kilometer",
    ucumCode: "kW.h/(100.km)",
  },
  { cldrCode: "frequency-gigahertz", label: "gigahertz", ucumCode: "GHz" },
  { cldrCode: "frequency-hertz", label: "hertz", ucumCode: "Hz" },
  { cldrCode: "frequency-kilohertz", label: "kilohertz", ucumCode: "kHz" },
  { cldrCode: "frequency-megahertz", label: "megahertz", ucumCode: "MHz" },
  { cldrCode: "graphics-dot", label: "dot", ucumCode: null },
  {
    cldrCode: "graphics-dot-per-centimeter",
    label: "dot per centimeter",
    ucumCode: null,
  },
  { cldrCode: "graphics-dot-per-inch", label: "dot per inch", ucumCode: null },
  { cldrCode: "graphics-em", label: "em", ucumCode: null },
  { cldrCode: "graphics-megapixel", label: "megapixel", ucumCode: null },
  { cldrCode: "graphics-pixel", label: "pixel", ucumCode: null },
  {
    cldrCode: "graphics-pixel-per-centimeter",
    label: "pixel per centimeter",
    ucumCode: null,
  },
  {
    cldrCode: "graphics-pixel-per-inch",
    label: "pixel per inch",
    ucumCode: null,
  },
  {
    cldrCode: "length-100-kilometer",
    label: "100 kilometer",
    ucumCode: "100.km",
  },
  {
    cldrCode: "length-astronomical-unit",
    label: "astronomic unit",
    ucumCode: "AU",
  },
  { cldrCode: "length-centimeter", label: "centimeter", ucumCode: "cm" },
  { cldrCode: "length-decimeter", label: "decimeter", ucumCode: "dm" },
  { cldrCode: "length-fathom", label: "fathom", ucumCode: "[fth_i]" },
  { cldrCode: "length-foot", label: "foot", ucumCode: "[ft_i]" },
  { cldrCode: "length-furlong", label: "furlong", ucumCode: "[fur_us]" },
  { cldrCode: "length-inch", label: "inch", ucumCode: "[in_i]" },
  { cldrCode: "length-kilometer", label: "kilometer", ucumCode: "km" },
  { cldrCode: "length-light-year", label: "light-year", ucumCode: "[ly]" },
  { cldrCode: "length-meter", label: "meter", ucumCode: "m" },
  { cldrCode: "length-micrometer", label: "micrometer", ucumCode: "um" },
  { cldrCode: "length-mile", label: "mile", ucumCode: "[mi_i]" },
  { cldrCode: "length-mile-scandinavian", label: "mil", ucumCode: "[mil_i]" },
  { cldrCode: "length-millimeter", label: "millimeter", ucumCode: "mm" },
  { cldrCode: "length-nanometer", label: "nanometer", ucumCode: "nm" },
  {
    cldrCode: "length-nautical-mile",
    label: "nautical mile",
    ucumCode: "[nmi_i]",
  },
  { cldrCode: "length-parsec", label: "parsec", ucumCode: "pc" },
  { cldrCode: "length-picometer", label: "picometer", ucumCode: "pm" },
  { cldrCode: "length-point", label: "point", ucumCode: "[pnt]" },
  { cldrCode: "length-yard", label: "yard", ucumCode: "[yd_i]" },
  { cldrCode: "length-earth-radius", label: "earth radius", ucumCode: null },
  { cldrCode: "length-solar-radius", label: "solar radius", ucumCode: null },
  { cldrCode: "light-candela", label: "candela", ucumCode: "cd" },
  { cldrCode: "light-lumen", label: "lumen", ucumCode: "lm" },
  { cldrCode: "light-lux", label: "lux", ucumCode: "lx" },
  {
    cldrCode: "light-solar-luminosity",
    label: "solar luminosity",
    ucumCode: null,
  },
  { cldrCode: "mass-carat", label: "carat", ucumCode: "[car_m]" },
  { cldrCode: "mass-grain", label: "grain", ucumCode: "[gr]" },
  { cldrCode: "mass-gram", label: "gram", ucumCode: "g" },
  { cldrCode: "mass-kilogram", label: "kilogram", ucumCode: "kg" },
  { cldrCode: "mass-tonne", label: "tonne", ucumCode: "t" },
  { cldrCode: "mass-microgram", label: "microgram", ucumCode: "ug" },
  { cldrCode: "mass-milligram", label: "milligram", ucumCode: "mg" },
  { cldrCode: "mass-ounce", label: "ounce", ucumCode: "[oz_av]" },
  { cldrCode: "mass-ounce-troy", label: "troy ounce", ucumCode: "[oz_tr]" },
  { cldrCode: "mass-pound", label: "pound", ucumCode: "[lb_av]" },
  { cldrCode: "mass-stone", label: "stone", ucumCode: "[stone_av]" },
  { cldrCode: "mass-ton", label: "ton", ucumCode: "[ston_av]" },
  { cldrCode: "mass-dalton", label: "dalton", ucumCode: null },
  { cldrCode: "mass-earth-mass", label: "Earth mass", ucumCode: null },
  { cldrCode: "mass-solar-mass", label: "solar mass", ucumCode: null },
  { cldrCode: "power-gigawatt", label: "gigawatt", ucumCode: "GW" },
  { cldrCode: "power-horsepower", label: "horsepower", ucumCode: "[HP]" },
  { cldrCode: "power-kilowatt", label: "kilowatt", ucumCode: "kW" },
  { cldrCode: "power-megawatt", label: "megawatt", ucumCode: "MW" },
  { cldrCode: "power-milliwatt", label: "milliwatt", ucumCode: "mW" },
  { cldrCode: "power-watt", label: "watt", ucumCode: "W" },
  { cldrCode: "pressure-atmosphere", label: "atmosphere", ucumCode: "atm" },
  { cldrCode: "pressure-hectopascal", label: "hectopascal", ucumCode: "hPa" },
  {
    cldrCode: "pressure-inch-ofhg",
    label: "inch of mercury",
    ucumCode: "[in_i'Hg]",
  },
  { cldrCode: "pressure-bar", label: "bar", ucumCode: "bar" },
  { cldrCode: "pressure-millibar", label: "millibar", ucumCode: "mbar" },
  {
    cldrCode: "pressure-millimeter-ofhg",
    label: "millimeter of mercury",
    ucumCode: "mm[Hg]",
  },
  {
    cldrCode: "pressure-pound-force-per-square-inch",
    label: "pound per square inch",
    ucumCode: "[psi]",
  },
  { cldrCode: "pressure-pascal", label: "pascal", ucumCode: "Pa" },
  { cldrCode: "pressure-kilopascal", label: "kilopascal", ucumCode: "kPa" },
  { cldrCode: "pressure-megapascal", label: "megapascal", ucumCode: "MPa" },
  { cldrCode: "pressure-ofhg", label: "unit of mercury", ucumCode: null },
  {
    cldrCode: "speed-kilometer-per-hour",
    label: "kilometer per hour",
    ucumCode: "km/h",
  },
  { cldrCode: "speed-knot", label: "knot", ucumCode: "[kn_i]" },
  {
    cldrCode: "speed-meter-per-second",
    label: "meter per second",
    ucumCode: "m/s",
  },
  {
    cldrCode: "speed-mile-per-hour",
    label: "mile per hour",
    ucumCode: "[mi_i]/h",
  },
  { cldrCode: "temperature-celsius", label: "degree Celsius", ucumCode: "Cel" },
  {
    cldrCode: "temperature-fahrenheit",
    label: "degree Fahrenheit",
    ucumCode: "[degF]",
  },
  {
    cldrCode: "temperature-generic",
    label: "temperature (generic)",
    ucumCode: null,
  },
  { cldrCode: "temperature-kelvin", label: "kelvin", ucumCode: "K" },
  {
    cldrCode: "torque-pound-force-foot",
    label: "pound-foot",
    ucumCode: "[lbf_av].[ft_i]",
  },
  { cldrCode: "torque-newton-meter", label: "newton meter", ucumCode: "N.m" },
  {
    cldrCode: "volume-acre-foot",
    label: "acre-foot",
    ucumCode: "[acr_us].[ft_i]",
  },
  { cldrCode: "volume-bushel", label: "bushel", ucumCode: "[bu_us]" },
  { cldrCode: "volume-centiliter", label: "centileter", ucumCode: "cL" },
  {
    cldrCode: "volume-cubic-centimeter",
    label: "cubic centimeter",
    ucumCode: "cm3",
  },
  { cldrCode: "volume-cubic-foot", label: "cubic foot", ucumCode: "[cft_i]" },
  { cldrCode: "volume-cubic-inch", label: "cubic inch", ucumCode: "[cin_i]" },
  {
    cldrCode: "volume-cubic-kilometer",
    label: "cubic kilometer",
    ucumCode: "km3",
  },
  { cldrCode: "volume-cubic-meter", label: "cubic meter", ucumCode: "m3" },
  { cldrCode: "volume-cubic-mile", label: "cubic mile", ucumCode: "[mi_i]3" },
  { cldrCode: "volume-cubic-yard", label: "cubic yard", ucumCode: "[cyd_i]" },
  { cldrCode: "volume-cup", label: "cup", ucumCode: "[cup_us]" },
  { cldrCode: "volume-cup-metric", label: "metric cup", ucumCode: "[cup_m]" },
  { cldrCode: "volume-deciliter", label: "decileter", ucumCode: "dL" },
  { cldrCode: "volume-dessert-spoon", label: "dessert-spoon", ucumCode: null },
  {
    cldrCode: "volume-dessert-spoon-imperial",
    label: "imperial dessert-spoon",
    ucumCode: null,
  },
  { cldrCode: "volume-drop", label: "drop", ucumCode: "[drp]" },
  { cldrCode: "volume-dram", label: "dram", ucumCode: "[dr_av]" },
  { cldrCode: "volume-jigger", label: "jigger", ucumCode: null },
  { cldrCode: "volume-pinch", label: "pinch", ucumCode: null },
  {
    cldrCode: "volume-quart-imperial",
    label: "imperial quart",
    ucumCode: "[qt_br]",
  },
  {
    cldrCode: "volume-fluid-ounce",
    label: "fluid ounce",
    ucumCode: "[foz_us]",
  },
  {
    cldrCode: "volume-fluid-ounce-imperial",
    label: "imperial fluid ounce",
    ucumCode: "[foz_br]",
  },
  { cldrCode: "volume-gallon", label: "gallon", ucumCode: "[gal_us]" },
  {
    cldrCode: "volume-gallon-imperial",
    label: "imperial gallon",
    ucumCode: "[gal_br]",
  },
  { cldrCode: "volume-hectoliter", label: "hectoliter", ucumCode: "hL" },
  { cldrCode: "volume-liter", label: "liter", ucumCode: "L" },
  { cldrCode: "volume-megaliter", label: "megaliter", ucumCode: "ML" },
  { cldrCode: "volume-milliliter", label: "milliliter", ucumCode: "mL" },
  { cldrCode: "volume-pint", label: "pint", ucumCode: "[pt_us]" },
  {
    cldrCode: "volume-pint-metric",
    label: "imperial pint",
    ucumCode: "[pt_br]",
  },
  { cldrCode: "volume-quart", label: "quart", ucumCode: "[qt_us]" },
  { cldrCode: "volume-tablespoon", label: "tablespoon", ucumCode: "[tbs_us]" },
  { cldrCode: "volume-teaspoon", label: "teaspoon", ucumCode: "[tsp_us]" },
  { cldrCode: "volume-barrel", label: "barrel", ucumCode: "[bbl_us]" },
];
