name: CI
on: [push]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Set Yarn 3.x
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          
      - name: Install
        run: |
          yarn install
          
      - name: Test
        run: |
          yarn workspaces foreach run test
